export const mockRequests = [
  {
    id: 1,
    data: '12/03/2024',
    product: 'Aço 1020',
    variation: 'MAT-ACO-1020-RED',
    quantity: '20 unid.',
    unitMeasure: 'Und',
    additionalInfoStatus: 'ajustes',
    items: [
      {
        id: 1,
        product: 'IMP-002 Impressora',
        variation: 'Leite Italac Desnatado',
        quantity: 2,
        unitMeasure: 'Und',
        status: 'ajustes',
      },
      {
        id: 2,
        product: 'MOU-003 Mouse',
        variation: 'Mouse Ergonômico',
        quantity: 1,
        unitMeasure: 'Caixas',
        status: 'ajustes',
      },
      {
        id: 3,
        product: 'LEI-022 Leite',
        variation: 'Epson Eco Tank',
        quantity: 3,
        unitMeasure: 'Und',
        status: 'ajustes',
      },
    ],
  },
  {
    id: 2,
    data: '12/12/2001',
    product: 'Aço 1020',
    variation: 'MAT-ACO-1020-RED',
    quantity: '30 m²',
    unitMeasure: 'm²',
    additionalInfoStatus: 'entregue',
    items: [],
  },
  {
    id: 3,
    data: '12/12/2001',
    product: 'Aço 1020',
    variation: 'MAT-ACO-1020-RED',
    quantity: '10 caixas',
    unitMeasure: 'Caixas',
    additionalInfoStatus: 'atrasada',
    items: [],
  },
  {
    id: 4,
    data: '12/12/2001',
    product: 'Aço 1020',
    variation: 'MAT-ACO-1020-RED',
    quantity: '30 m²',
    unitMeasure: 'm²',
    additionalInfoStatus: 'cancelado',
    items: [],
  },
  {
    id: 5,
    data: '12/12/2001',
    product: 'Aço 1020',
    variation: 'MAT-ACO-1020-RED',
    quantity: '20 unid.',
    unitMeasure: 'Und',
    additionalInfoStatus: 'parcial',
    items: [],
  },
  {
    id: 6,
    data: '12/12/2001',
    product: 'Aço 1020',
    variation: 'MAT-ACO-1020-RED',
    quantity: '30 m²',
    unitMeasure: 'm²',
    additionalInfoStatus: 'atendimento',
    items: [],
  },
];
